#!/bin/sh

set -e

if ! [ -d /Volumes ]; then
  sudo apt-get install -y ruby lshw lsb-release dmidecode 
fi

RUBYLIB=`dirname $0`/freegeek-build-utils/lib:`dirname $0`/rubytui/lib  `dirname $0`/freegeek-build-utils/scripts/printme
